medpy.core.exceptions.ArgumentError
===================================

.. currentmodule:: medpy.core.exceptions

.. autoexception:: ArgumentError