medpy.core.exceptions.MetaDataError
===================================

.. currentmodule:: medpy.core.exceptions

.. autoexception:: MetaDataError