medpy.core.exceptions.FunctionError
===================================

::: {.currentmodule}
medpy.core.exceptions
:::

::: {.autoexception}
FunctionError
:::
